apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../base
patchesStrategicMerge:
  - autoscaler/helmrelease.yaml
patches:
  - target:
      version: v1
      kind: Ingress
      name: hello-world
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: hello-world.dev.mikesupertrampster.com
  - target:
      version: v1
      kind: Ingress
      name: kiali
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: kiali.dev.mikesupertrampster.com
  - target:
      version: v1
      kind: Ingress
      name: alertmanager
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: alertmanager.dev.mikesupertrampster.com
  - target:
      version: v1
      kind: Ingress
      name: prometheus
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: prometheus.dev.mikesupertrampster.com
  - target:
      version: v2beta1
      kind: HelmRelease
      name: datadog
    patch: |
      - op: replace
        path: /spec/values/datadog/clusterName
        value: dev