apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../base
patches:
  - target:
      version: v1
      kind: Ingress
      name: hello-world
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: hello-world.dev.mikesupertrampster.com