---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: autoscaler
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: cluster-autoscaler
      version: 9.17.1
      sourceRef:
        kind: HelmRepository
        name: autoscaler
        namespace: flux-system
  values:
    autoDiscovery:
      clusterName: EKS
    rbac:
      serviceAccount:
        annotations:
          "eks.amazonaws.com/role-arn": arn:aws:iam::639369124033:role/EKSClusterAutoscaler