---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: datadog
  namespace: datadog
spec:
  interval: 5m
  chart:
    spec:
      chart: datadog
      version: 2.32.3
      sourceRef:
        kind: HelmRepository
        name: datadog
        namespace: flux-system
  values:
    datadog:
      apiKeyExistingSecret: datadog
      appKeyExistingSecret: datadog
      clusterName: EKS
      loglevel: WARN
      collectEvents: true
