---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: telemetry
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana
      version: 6.26.3
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Prometheus
            type: prometheus
            access: proxy
            isDefault: true
            url: http://prometheus-server.prometheus.svc.cluster.local
    grafana.ini:
      analytics:
        check_for_updates: true
      auth.anonymous:
        enabled: true
        org_role: Admin