---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: telemetry
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana
      version: 6.26.3
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
