---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jaeger
  namespace: telemetry
spec:
  interval: 5m
  chart:
    spec:
      chart: jaeger
      version: 0.55.0
      sourceRef:
        kind: HelmRepository
        name: jaegertracing
        namespace: flux-system
  values:
    admin:
      existingSecret: grafana