---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: telemetry
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      version: 2.11.0
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system