---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.0.19
      sourceRef:
        kind: HelmRepository
        name: nginx-stable
        namespace: flux-system
  values:
    controller:
      service:
        type: NodePort
        nodePorts:
          http: 30080
          https: 30081