---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.0.19
      sourceRef:
        kind: HelmRepository
        name: nginx-stable
        namespace: flux-system
  values:
    controller:
      service:
        type: NodePort
        nodePorts:
          http: 30080
          https: 30081
          tcp:
            "30000": "65000"

---
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-external
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
spec:
  type: ExternalName
  externalName: dev-1765100973.eu-west-1.elb.amazonaws.com
