---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: spinnaker
  namespace: spinnaker
spec:
  helmVersion: v3
  chart:
    name: spinnaker
    repository: https://helmcharts.opsmx.com
    version: 2.2.7