apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: default
spec:
  ports:
    - name: nginx
      port: 80
      targetPort: 8080
  selector:
    app: nginx

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  defaultBackend:
    resource:
      apiGroup: k8s.example.com
      kind: StorageBucket
      name: static-assets
  rules:
    - host: nginx.dev.mikesupertrampster.com
      http:
        paths:
          - pathType: Prefix
            path: "/nginx"
            backend:
              service:
                name: nginx
                port:
                  number: 80