apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - autoscaler
#  - datadog
  - flux
#  - ingress-nginx
#  - istio
#  - kiali
#  - kube-hunter
#  - kubecost
#  - prometheus
#  - telemetry
  - demos/hello-world
