---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: datadog
  namespace: datadog
spec:
  interval: 5m
  chart:
    spec:
      chart: datadog
      version: 2.32.3
      sourceRef:
        kind: HelmRepository
        name: datadog
        namespace: flux-system
  values:
    datadog:
      env:
        - name: DD_LOGS_CONFIG_K8S_CONTAINER_USE_FILE
          value: "true"
      apiKeyExistingSecret: datadog
      appKeyExistingSecret: datadog
      clusterName: EKS
      loglevel: WARN
      collectEvents: true
      logs:
        enabled: true
        containerCollectAll: true
      networkMonitoring:
        enabled: true
      orchestratorExplorer:
        enabled: true
      processAgent:
        processCollection: true
      systemProbe:
        collectDNSStats: true