---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: datadog
  namespace: datadog
spec:
  interval: 5m
  chart:
    spec:
      chart: datadog
      version: 2.33.0
      sourceRef:
        kind: HelmRepository
        name: datadog
        namespace: flux-system
  values:
    datadog:
      env:
        - name: DD_LOGS_CONFIG_K8S_CONTAINER_USE_FILE
          value: "true"
#        - name: DD_PROCESS_AGENT_ENABLED
#          value: 'true'
#        - name: DD_SYSTEM_PROBE_ENABLED
#          value: 'true'
#        - name: DD_SYSTEM_PROBE_EXTERNAL
#          value: 'true'
#        - name: DD_SYSPROBE_SOCKET
#          value: /var/run/sysprobe/sysprobe.sock
      apiKeyExistingSecret: datadog
      appKeyExistingSecret: datadog
      clusterName: EKS
      loglevel: WARN
      collectEvents: true
      logs:
        enabled: true
        containerCollectAll: true
      networkMonitoring:
        enabled: true
#      processAgent:
#        processCollection: true
#      systemProbe:
#        collectDNSStats: true
      containerExcludeLogs: "name:kube-state-metrics name:cluster-autoscaler name:source-controller name:helm-controller name:loki name:controller name:agent"
