apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kiali-server
  namespace: istio-system
spec:
  interval: 5m
  chart:
    spec:
      chart: kiali-server
      version: 1.49.0
      sourceRef:
        kind: HelmRepository
        name: kiali
        namespace: flux-system
  values:
    external_services:
      prometheus:
        url: "http://prometheus-server.prometheus.svc.cluster.local/"