---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: prometheus
spec:
  interval: 5m
  chart:
    spec:
      chart: prometheus
      version: 15.9.0
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: flux-system
  values:
    alertmanager:
      persistentVolume:
        storageClass: gp2
    server:
      persistentVolume:
        storageClass: gp2

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: prometheus
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana
      version: 6.29.5
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    grafana.ini:
      auth.anonymous:
        enabled: true
        org_role: Admin
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: prometheus
            type: prometheus
            url: http://prometheus-server.prometheus.svc.cluster.local
            access: proxy
            isDefault: true
