---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: prometheus
spec:
  interval: 5m
  chart:
    spec:
      chart: prometheus
      version: 15.8.4
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: flux-system
  values:
    alertmanager:
      persistentVolume:
        storageClass: gp2
    server:
      persistentVolume:
        storageClass: gp2