name: Snyk Infrastructure as Code
on: pull_request
jobs:
  snyk:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Run Snyk Scanning for security issues
        continue-on-error: true
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          file: .